import { forwardRef } from 'react'
import { classNames } from '../utils'

type IconProps = {
  colorPreset?: 1 | 2 | 3 | 4
  size?: 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl'
  rotate?: 90 | 180 | 270
  textStart?: boolean
  textEnd?: boolean
  icon:
    | '1177'
    | 'activity-missed'
    | 'agent'
    | 'ai'
    | 'arrow-down'
    | 'arrow-down-small'
    | 'arrow-left'
    | 'arrow-left-small'
    | 'arrow-right'
    | 'arrow-right-small'
    | 'arrow-up'
    | 'arrow-up-small'
    | 'assistive-devices'
    | 'atl'
    | 'attention'
    | 'book'
    | 'calendar'
    | 'call'
    | 'call-list'
    | 'call-ongoing'
    | 'camera-off'
    | 'camera-on'
    | 'camera-switch'
    | 'caregiver'
    | 'chart-line'
    | 'chat'
    | 'check'
    | 'check-small'
    | 'chevron-down'
    | 'chevron-down-small'
    | 'chevron-left'
    | 'chevron-left-small'
    | 'chevron-right'
    | 'chevron-right-small'
    | 'chevron-up'
    | 'chevron-up-small'
    | 'clipboard'
    | 'clipboard-with-cross'
    | 'clipboard-with-text'
    | 'close'
    | 'close-small'
    | 'compare'
    | 'compare-small'
    | 'copy-file'
    | 'copy-link'
    | 'copy-link-small'
    | 'denied-small'
    | 'desktop'
    | 'doctors-bag'
    | 'document'
    | 'download'
    | 'download-small'
    | 'drag-n-drop'
    | 'drag-n-drop-small'
    | 'drug'
    | 'e-mail'
    | 'e-mail-sent'
    | 'e-mail-unread'
    | 'edit'
    | 'ef'
    | 'error'
    | 'error-filled'
    | 'exclamation-mark'
    | 'expand'
    | 'expand-small'
    | 'external-link'
    | 'external-link-small'
    | 'file-csv'
    | 'file-excel'
    | 'file-image'
    | 'file-other'
    | 'file-pdf'
    | 'file-ppt'
    | 'file-word'
    | 'find-care'
    | 'find-region'
    | 'flag'
    | 'folder'
    | 'form-numbered'
    | 'form-numbered-reoccurring'
    | 'fsub'
    | 'fsub-alt'
    | 'fsub-f'
    | 'functions'
    | 'group'
    | 'headphones'
    | 'hospital'
    | 'hourglass'
    | 'hourglass-end'
    | 'hourglass-start'
    | 'house'
    | 'id-card'
    | 'id-card-locked'
    | 'image'
    | 'inactivity'
    | 'inera'
    | 'information'
    | 'lightbulb'
    | 'list'
    | 'listen'
    | 'locked'
    | 'log'
    | 'log-locked'
    | 'm-info'
    | 'medical-transportation'
    | 'menu'
    | 'menu-small'
    | 'minus'
    | 'minus-small'
    | 'mobile'
    | 'moment-start'
    | 'moment-stop'
    | 'monitoring'
    | 'narcotics-ii'
    | 'narcotics-iii'
    | 'narcotics-iv-v'
    | 'nlm'
    | 'notification'
    | 'office-building'
    | 'organization'
    | 'play'
    | 'plus'
    | 'plus-small'
    | 'prescription'
    | 'prescription-label'
    | 'prescription-label-alt'
    | 'prescription-label-alt-small'
    | 'prescription-label-s'
    | 'prescription-label-s-small'
    | 'prescription-label-small'
    | 'print'
    | 'question'
    | 'registered'
    | 'reload'
    | 'reload-small'
    | 'reply'
    | 'reply-small'
    | 'search'
    | 'settings'
    | 'share'
    | 'share-small'
    | 'shield-locked-filled'
    | 'shield-locked-outlined'
    | 'social-facebook'
    | 'social-linkedin'
    | 'social-x'
    | 'star'
    | 'star-filled'
    | 'success'
    | 'swap-horizontal'
    | 'swap-horizontal-small'
    | 'swap-vertical'
    | 'swap-vertical-small'
    | 'switch-person'
    | 'toggle-card-view'
    | 'toggle-list-view'
    | 'trash-can'
    | 'trademark'
    | 'tube-analysis'
    | 'tube-empty'
    | 'tube-filled'
    | 'tvbl'
    | 'unlocked'
    | 'user'
    | 'vbl'
    | 'video-off'
    | 'video-on'
    | 'video-switch'
    | 'visibility'
    | 'visibility-off'
    | 'warning'
} & React.HTMLAttributes<HTMLSpanElement>

export const Icon = forwardRef<HTMLSpanElement, IconProps>(
  ({ icon, colorPreset, size, rotate, textStart = false, textEnd = false, className, ...props }, ref) => (
    <span
      ref={ref}
      className={classNames(
        `ids-icon-${icon}`,
        colorPreset && `ids-icon--color-preset-${colorPreset}`,
        size && `ids-icon--${size}`,
        rotate && `ids-icon--rotate-${rotate}`,
        textStart && 'ids-icon--text-start',
        textEnd && 'ids-icon--text-end',
        className
      )}
      {...props}
    />
  )
)

Icon.displayName = 'Icon'
