version: "3.8"

services:

  frontend:
    build:
      dockerfile: Dockerfile.webcert
    image: webcert/frontend:latest
    pull_policy: always
    restart: always
    container_name: webcert-frontend
    ports:
      - "3000:8080"
    environment:
      - WEBCERT_API=host.docker.internal:8020
