FROM nginx
COPY nginx/templates/default.conf.template /etc/nginx/conf.d/default.conf
COPY nginx/templates/intyg.conf.template /etc/nginx/conf.d/intyg.conf
COPY nginx/conf/nginx.conf /etc/nginx/nginx.conf
