kind: Template
apiVersion: v1
metadata:
  name: pipelinetemplate-test-frontend
parameters:
  - name: APP_NAME
    required: true
  - name: RELEASE_VERSION
    required: true
  - name: STAGE
    required: true
    value: "test"
  - name: ARTIFACT_IMAGE_SUFFIX
    required: true
    value: "artifact"
  - name: GIT_URL
    required: true
  - name: GIT_CI_BRANCH
    required: true
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}-${RELEASE_VERSION}-test-pipeline
      generation: 1
      labels:
        app: ${APP_NAME}
        release: ${RELEASE_VERSION}
        stage: ${STAGE}
    spec:
      runPolicy: "SerialLatestOnly"
      triggers:
        - type: "ImageChange"
          imageChange:
            from:
              kind: "ImageStreamTag"
              name: "webcert-frontend:latest"
      source:
        git:
          uri: "${GIT_URL}"
          ref: "refs/heads/${GIT_CI_BRANCH}"
      strategy:
        jenkinsPipelineStrategy:
          type: JenkinsPipeline
          env:
            - name: "APP_NAME"
              value: "${APP_NAME}"
            - name: "RELEASE_VERSION"
              value: "${RELEASE_VERSION}"
            - name: "STAGE"
              value: "${STAGE}"
            - name: "ARTIFACT_IMAGE_SUFFIX"
              value: "${ARTIFACT_IMAGE_SUFFIX}"
            - name: "GIT_BRANCH"
              value: "${GIT_CI_BRANCH}"
            - name: "GIT_URL"
              value: "${GIT_URL}"
          jenkinsfilePath: openshift/test-pipeline/Jenkinsfile
