apiVersion: v1
kind: Template
metadata:
  name: testrunnertemplate-pod
parameters:
- name: APP_NAME
  required: true
- name: STAGE
  required: true
  value: "test"
- name: TARGET_URL
  required: true
- name: ACTUATOR_URL
  required: false
- name: JOB_NAME
  required: true
- name: BUILD_VERSION
  required: true
- name: CALLBACK_URL
  required: true
- name: BUILD_TAG
  required: true
- name: IMAGE
  required: true
- name: TESTS
  required: true
- name: NO_PROXY
  required: true
  value: "*"
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: "${BUILD_TAG}"
    labels:
      app: ${APP_NAME}
      stage: ${STAGE}
  spec:
    containers:
      - env:
        - name: TARGET_URL
          value: ${TARGET_URL}
        - name: ACTUATOR_URL
          value: ${ACTUATOR_URL}
        - name: CALLBACK_URL
          value: ${CALLBACK_URL}
        - name: REPORT_DIR
          value: /mnt/reports/${JOB_NAME}/${BUILD_VERSION}
        - name: JAVA_OPTS
          value: "-Xmx512M"
        - name: NO_PROXY
          value: ${NO_PROXY}
        - name: no_proxy
          value: ${NO_PROXY}
        resources:
          limits:
            cpu: 1
            memory: 2304Mi
          requests:
            cpu: 100m
            memory: 2Gi
        image: ${IMAGE}
        imagePullPolicy: Always
        name: ${BUILD_TAG}
        command: [ "/usr/libexec/s2i/run", "testrun", "${TESTS}" ]
        volumeMounts:
        - mountPath: /mnt/reports
          name: rep-vol
    restartPolicy: Never
    volumes:
      - name: rep-vol
        persistentVolumeClaim:
          claimName: "jenkins-reports"

