export { IDSHeaderAvatar as IDSHeaderAvatarElement } from '@inera/ids-core/components/header/avatar/header-avatar-element'
export * from './IDSHeader'
export * from './IDSHeaderItem'
export * from './IDSHeaderMobileMenu'
export * from './avatar/IDSHeaderAvatar'
export * from './navigation/IDSHeaderMobileItem'
export * from './navigation/IDSHeaderNav'
export * from './navigation/IDSHeaderNavItem'
