export { IDSHeaderAvatar as IDSHeaderAvatarElement } from '@inera/ids-core/components/header/avatar/header-avatar-element'
export * from './IDSHeader'
export * from './IDSHeaderAvatar'
export * from './IDSHeaderItem'
export * from './IDSHeaderMobileMenu'
export * from './IDSHeaderNav'
export * from './IDSHeaderNavItem'
