kind: Template
apiVersion: v1
metadata:
  name: buildtemplate-frontend
parameters:
  - name: APP_NAME
    required: true
    value: "webcert-frontend"
  - name: IS_APP_NAME
    required: true
    value: "webcert-frontend"
  - name: ARTIFACT_IMAGE_SUFFIX
    required: true
    value: "artifact"
  - name: STAGE
    required: true
    value: "test"
  - name: BUILD_VERSION
    required: true
    value: "latest"
  - name: E_UID
    value: "1000310000"
    required: true
  - name: BUILDER_IMAGE
    required: true
    value: "s2i-frontend-builder:latest"
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 1200
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 2Gi
      source:
        contextDir: /
        type: Binary
      strategy:
        sourceStrategy:
          env:
            - name: APP_NAME
              value: ${APP_NAME}
            - name: STAGE
              value: ${STAGE}
            - name: BUILD_VERSION
              value: ${BUILD_VERSION}
            - name: BUILDER_IMAGE
              value: ${BUILDER_IMAGE}
          from:
            kind: "ImageStreamTag"
            name: ${BUILDER_IMAGE}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 600
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${IS_APP_NAME}:${BUILD_VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 2Gi
      source:
        dockerfile: |-
          FROM nginx-frontend-base:latest

          # Set working directory to nginx asset directory
          WORKDIR /usr/share/nginx/html

          # Remove default nginx static assets
          RUN rm -rf ./*

          COPY ./build/ .
          COPY ./nginx/templates /etc/nginx/templates/
          COPY ./nginx/conf/nginx.conf /etc/nginx/nginx.conf

          # comment user directive as master process is run as user in OpenShift anyhow
          RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf

          EXPOSE 8080
        images:
            - from:
                kind: ImageStreamTag
                name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
              paths:
                - sourcePath: /tmp/artifacts/.
                  destinationDir: "."
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: nginx-frontend-base:latest
        type: Docker
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}-verified
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
