name: Update browserslist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Update browserslist
        run: npx update-browserslist-db@latest

      - name: Check for changes
        id: changes
        run: |
          if git diff --exit-code; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create or update PR
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update caniuse-lite database'
          title: 'chore: update caniuse-lite database'
          body: 'This PR updates the `caniuse-lite` database to the latest version.'
          branch: 'chore/update-caniuse-lite'
          base: 'main'
          delete-branch: true
