# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [master, 'project/**']
  pull_request:
    branches: [master, 'project/**']

jobs:
  get-changed-workspaces:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.changed-packages.outputs.names }}
      paths: ${{ steps.changed-packages.outputs.paths }}
      empty: ${{ steps.changed-packages.outputs.empty }}
    steps:
      - uses: actions/checkout@v2
      - name: Find changed workspaces
        uses: AlexShukel/get-changed-workspaces-action@v1.0.0
        id: changed-packages
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: reviewdog/action-eslint@v1
  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest
    if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
    needs: [get-changed-workspaces]
    strategy:
      matrix:
        name: ${{ fromJson(needs.get-changed-workspaces.outputs.names) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn workspace ${{ matrix.name }} tsc --noEmit
  jest:
    name: runner / jest
    runs-on: ubuntu-latest
    # if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
    needs: [get-changed-workspaces]
    strategy:
      matrix:
        name: ${{ fromJson(needs.get-changed-workspaces.outputs.names) }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - id: packageInfo
        run: |
          info=$(yarn workspaces info | jq '.${{ matrix.name }}')
          echo "::set-output name=info::$info"
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          skip-step: install
          output: report-markdown
          working-directory: ${{ fromJson(steps.packageInfo.outputs.info) }}
          test-script: yarn workspace ${{ matrix.name }} test:gh
          package-manager: yarn
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
