# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [master, 'project/**']
  pull_request:
    branches: [master, 'project/**']

jobs:
  get-changed-workspaces:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.changed-packages.outputs.names }}
      paths: ${{ steps.changed-packages.outputs.paths }}
      empty: ${{ steps.changed-packages.outputs.empty }}
    steps:
      - uses: actions/checkout@v2
      - name: Find changed workspaces
        uses: AlexShukel/get-changed-workspaces-action@v1.0.0
        id: changed-packages
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: reviewdog/action-eslint@v1
  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest
    needs: [get-changed-workspaces]
    strategy:
      matrix:
        name: ${{ fromJson(needs.get-changed-workspaces.outputs.names) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @frontend/${{ matrix.name }} tsc --noEmit
  jest:
    name: runner / jest
    runs-on: ubuntu-latest
    needs: [get-changed-workspaces]
    strategy:
      matrix:
        name: ${{ fromJson(needs.get-changed-workspaces.outputs.names) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @frontend/${{ matrix.name }} test:ci
  coverage:
    name: runner / coverage
    runs-on: ubuntu-latest
    needs: [jest, get-changed-workspaces]
    strategy:
      matrix:
        name: ${{ fromJson(needs.get-changed-workspaces.outputs.names) }}
        path: ${{ fromJson(needs.get-changed-workspaces.outputs.paths) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          coverage-file: ${{ matrix.path }}/coverage/coverage-final.json
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
