# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Setup workspace
        run: yarn install
      - name: Compile TypeScript Common
        run: yarn workspace @frontend/common tsc
      - name: Compile TypeScript Webcert
        run: yarn workspace @frontend/webcert tsc
      - name: Test Common
        run: yarn workspace @frontend/common test:ci
      - name: Test webcert
        run: yarn workspace @frontend/webcert test:ci
